sample:
  user: root
  host: localhost
  port: 2222
  java: 8
  tomcat:
    host: localhost
    version: 8.0.22
    base: /tmp
    memory: 198
    username: tomcat
    password: tomcat
    ports:
      http: 8101
      ajp: 6101
      jmx: 9601
      shutdown: 7101
      redirect: 9101
  monit:
    host: localhost
    home: /mnt/data/aplicacions/cron/
