production:
    user: root
    host: localhost
    port: 2222
    tomcat:
        host: localhost
        port: 8888
        user: tomcat
        password: tomcat
        home: /usr/share/apache-tomcat-8.0.23
    monit:
        host: localhost
        home: /mnt/data/aplicacions/cron/