sample:
    user: root
    host: ship-deploy-server
    port: 22
    java: 8
    tomcat:
        host: ship-deploy-server
        version: 8.0.26
        base: /usr/share
        memory: 198
        username: tomcat
        password: tomcat
        ports:
            http: 8080
            ajp: 6101
            jmx: 9601
            shutdown: 7101
            redirect: 9101
    monit:
        host: ship-webapp-server
        home: /mnt/data/aplicacions/cron/
